#!/bin/ash

#/**
# * @author              $Author: bdapon $
# * @file:               make_rootfs.sh
# * @version             $Rev: 44 $
# * @date                $Date: 2008-12-16 17:48:16 +0100 (mar, 16 déc 2008) $
# *
# * Script de demarrage
# *
# */


# System Startup Script
# 
. /etc/init.d/functions

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t tmpfs -o mode=0755 none /dev
/bin/mkdir /dev/pts
/bin/mkdir /dev/shm
/bin/echo "/sbin/mdev" > /proc/sys/kernel/hotplug
/sbin/mdev -s

mkdir /var/log /var/run
echo -n "Cleaning up system: "
> /var/run/utmp
touch /var/log/wtmp
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0660 /var/log/messages
rm -f /var/run/*.pid
check_status

echo -n "Setting up interface lo: "
ifconfig lo up 127.0.0.1
check_status

echo -e "\\033[1;33m" "        _              _  _     __               "
echo -e "\\033[1;33m" "       | |            | || |   / _|              "
echo -e "\\033[1;33m" "   ___ | |  ___   ___ | || |_ | |_  _   _  _ __  "
echo -e "\\033[1;33m" "  / _ \| | / _ \ / __||__   _||  _|| | | || '_ \ "
echo -e "\\033[1;33m" " |  __/| ||  __/| (__    | |  | |  | |_| || | | |"
echo -e "\\033[1;33m" "  \___||_| \___| \___|   |_|  |_|   \__,_||_| |_|"
echo -e "\\033[1;33m" "                                                 "
echo -e "\\033[1;33m" ""
echo -e "\\033[37;44m" "Franck Jullien - www.elec4fun.fr - 2012           \\033[0m"

echo "Running start scripts."
for i in /etc/rc.d/start/*
do
        if [ -x $i ]; then
                $i start
        fi
done
